server:
  port: 8991
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
    gateway:
      routes:
        - id: users_route  # 指定路由唯一标识
          uri: lb://users  # 指定路由服务的地址
          predicates:
            - Path=/user/* # 指定路由规则
        - id: products_route
          uri: lb://products
          predicates:
            - Path=/product/**
      discovery:
        locator:
          enabled: true                            #开启根据服务名动态获取路


management:
  endpoints:
    web:
      exposure:
        include: "*"   #开启所有web端点暴露

