server:
  port: 8989

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
      - id: user_route                            # 指定路由唯一标识
#        uri: http://localhost:9999/ # 指定路由服务的地址
        uri: lb://users    # lb代表转发后台服务使用负载均衡,users代表服务注册中心consul上的服务名
        predicates:
        - Path=/feign/**                      # 指定路由规则
#        - After=2021-01-11T17:10:30.150+08:00[Asia/Shanghai]
#        - Before=2021-01-11T17:15:30.150+08:00[Asia/Shanghai]

      - id: product_route
#        uri: http://localhost:9998/
        uri: lb://products          # lb(loadbalance)代表负载均衡转发路由
        predicates:
        - Path=/product/**
        filters:
        - AddRequestParameter=id,21
        - AddResponseHeader=username,xizi
      discovery:
        locator:
          enabled: true                            #开启根据服务名动态获取路由

management:
  endpoints:
    web:
      exposure:
        include: "*"   #开启所有web端点暴露